/**
 * SceneWeaver Story Data
 * Auto-generated by build_story_from_md.py
 * DO NOT EDIT MANUALLY
 */

var story = {
  "ending_good": {
    "id": "ending_good",
    "bg": "forest.svg",
    "set_key_flags": [
      "ending_discovered"
    ],
    "textBlocks": [
      "The fox leads you to a hidden shrine deep in the forest.",
      "Congratulations! You've discovered the secret ending.",
      "Thank you for playing this SceneWeaver demo!"
    ],
    "choices": [
      {
        "label": "Play again",
        "target": "intro"
      }
    ]
  },
  "forest": {
    "id": "forest",
    "bg": "forest.svg",
    "set_flags": [
      "visited_forest"
    ],
    "textBlocks": [
      "You venture into the dark forest. The trees tower above you, blocking out most of the sunlight.",
      "A rustling in the bushes catches your attention."
    ],
    "choices": [
      {
        "label": "Investigate the sound",
        "target": "forest_creature"
      },
      {
        "label": "Return to the crossroads",
        "target": "intro"
      }
    ]
  },
  "forest_creature": {
    "id": "forest_creature",
    "bg": "forest.svg",
    "textBlocks": [
      "A small fox emerges from the bushes. It looks at you curiously, then scampers away into the woods.",
      "Perhaps it wanted to lead you somewhere?"
    ],
    "choices": [
      {
        "label": "Follow the fox",
        "target": "ending_good"
      },
      {
        "label": "Return to the forest entrance",
        "target": "forest"
      }
    ]
  },
  "intro": {
    "id": "intro",
    "bg": "forest.svg",
    "textBlocks": [
      "Welcome to SceneWeaver, a markdown-first visual novel engine.",
      "This is the second text block. It appears after you click Continue.",
      "Now you'll see some choices below. Pick one to continue the story."
    ],
    "choices": [
      {
        "label": "Go to the forest",
        "target": "forest"
      },
      {
        "label": "Visit the village",
        "target": "village"
      },
      {
        "label": "Check your inventory",
        "target": "inventory",
        "require_flags": [
          "has_map"
        ]
      }
    ]
  },
  "village": {
    "id": "village",
    "bg": "village.svg",
    "set_flags": [
      "visited_village"
    ],
    "set_key_flags": [
      "has_map"
    ],
    "textBlocks": [
      "The village is small but welcoming. An old merchant waves you over.",
      "\"Here, take this map. It will help you on your journey.\"\n\nYou received a map!"
    ],
    "choices": [
      {
        "label": "Thank the merchant",
        "target": "village_thanks"
      },
      {
        "label": "Return to the crossroads",
        "target": "intro"
      }
    ]
  },
  "village_thanks": {
    "id": "village_thanks",
    "bg": "village.svg",
    "textBlocks": [
      "The merchant smiles warmly. \"Safe travels, young adventurer!\""
    ],
    "choices": [
      {
        "label": "Continue exploring",
        "target": "intro"
      }
    ]
  }
};
